id: e0696a23-4b64-483c-808a-35bd2c9571e3
name: first_plugin
language: PYTHON27
hostTypes:
- UNIX
pluginType: STAGED
entryPoint: plugin_runner:plugin
srcDir: src
schemaFile: schema.json
buildNumber: 0.1.0
